### ISSUE TITLE
Implementació de la indexació de continguts GUSITE amb SOLR

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#51]
Es sol·licita incorporar al backoffice de GUSITE les funcions necessàries per realitzar la indexació de continguts (online/manual) amb SOLR.
Es sol·licita també eliminar del repositori de codi les classes i llibreries utilitzades per la indexació amb Lucene.

**Comment by slromero-indra** [comment]
Buenas, ya está comiteado todos los cambios referentes a la integración de solr en gusite.

**Comment by sgelabert-dgtic** [comment]
L'accés a l'opció principal de menú "Eines" --> "Crear indexació" no funciona:

`2016-12-01 11:42:40,838 ERROR [org.apache.struts.action.RequestProcessor] (http-10.215.9.158-28080-2) Invalid path /indexarMicrosite was requested`

**Comment by sgelabert-dgtic** [comment]
Error al crear la indexació
```
13:59:54,634 ERROR [LogInterceptor] EJBException in method: public abstract java.lang.Boolean es.caib.gusite.micropersistence.intf.SolrPendienteProcesoFacade.indexarMicrosite(java.lang.Long) throws es.caib.gusite.micropersistence.delegate.DelegateException,java.rmi.RemoteException, causedBy:
java.lang.NullPointerException
	at es.caib.solr.api.util.Utilidades.crearSolrClient(Utilidades.java:512)
	at es.caib.solr.api.impl.SolrIndexerImpl.desindexarRaiz(SolrIndexerImpl.java:620)
	at es.caib.gusite.micropersistence.ejb.SolrPendienteProcesoFacadeEJB.indexarMicrosite(SolrPendienteProcesoFacadeEJB.java:251)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.invocation.Invocation.performCall(Invocation.java:397)
	at org.jboss.ejb.StatelessSessionContainer$ContainerInterceptor.invoke(StatelessSessionContainer.java:233)
	at org.jboss.resource.connectionmanager.CachedConnectionInterceptor.invoke(CachedConnectionInterceptor.java:156)
	at org.jboss.ejb.plugins.StatelessSessionInstanceInterceptor.invoke(StatelessSessionInstanceInterceptor.java:173)
	at org.jboss.ejb.plugins.CallValidationInterceptor.invoke(CallValidationInterceptor.java:63)
	at org.jboss.ejb.plugins.AbstractTxInterceptor.invokeNext(AbstractTxInterceptor.java:121)
	at org.jboss.ejb.plugins.TxInterceptorCMT.runWithTransactions(TxInterceptorCMT.java:315)
	at org.jboss.ejb.plugins.TxInterceptorCMT.invoke(TxInterceptorCMT.java:181)
	at org.jboss.ejb.plugins.SecurityInterceptor.process(SecurityInterceptor.java:281)
	at org.jboss.ejb.plugins.SecurityInterceptor.invoke(SecurityInterceptor.java:211)
	at org.jboss.ejb.plugins.security.PreSecurityInterceptor.process(PreSecurityInterceptor.java:167)
	at org.jboss.ejb.plugins.security.PreSecurityInterceptor.invoke(PreSecurityInterceptor.java:84)
	at org.jboss.ejb.plugins.LogInterceptor.invoke(LogInterceptor.java:205)
	at org.jboss.ejb.plugins.ProxyFactoryFinderInterceptor.invoke(ProxyFactoryFinderInterceptor.java:138)
	at org.jboss.ejb.SessionContainer.internalInvoke(SessionContainer.java:650)
	at org.jboss.ejb.Container.invoke(Container.java:1092)
	at sun.reflect.GeneratedMethodAccessor358.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.jboss.mx.interceptor.ReflectedDispatcher.invoke(ReflectedDispatcher.java:157)
	at org.jboss.mx.server.Invocation.dispatch(Invocation.java:96)
	at org.jboss.mx.server.Invocation.invoke(Invocation.java:88)
	at org.jboss.mx.server.AbstractMBeanInvoker.invoke(AbstractMBeanInvoker.java:264)
	at org.jboss.mx.server.MBeanServerImpl.invoke(MBeanServerImpl.java:668)
	at org.jboss.invocation.local.LocalInvoker$MBeanServerAction.invoke(LocalInvoker.java:169)
	at org.jboss.invocation.local.LocalInvoker.invoke(LocalInvoker.java:118)
	at org.jboss.invocation.InvokerInterceptor.invokeLocal(InvokerInterceptor.java:260)
	at org.jboss.invocation.InvokerInterceptor.invoke(InvokerInterceptor.java:246)
	at org.jboss.proxy.TransactionInterceptor.invoke(TransactionInterceptor.java:61)
	at org.jboss.proxy.ejb.SecurityContextInterceptor.invoke(SecurityContextInterceptor.java:64)
	at org.jboss.proxy.SecurityInterceptor.invoke(SecurityInterceptor.java:68)
	at org.jboss.proxy.ejb.StatelessSessionInterceptor.invoke(StatelessSessionInterceptor.java:112)
	at org.jboss.proxy.ClientContainer.invoke(ClientContainer.java:101)
	at com.sun.proxy.$Proxy427.indexarMicrosite(Unknown Source)
	at es.caib.gusite.micropersistence.delegate.SolrPendienteProcesoDelegate.indexarMicrosite(SolrPendienteProcesoDelegate.java:51)
	at es.caib.gusite.microback.utils.job.IndexacionJob.execute(IndexacionJob.java:71)
	at org.quartz.core.JobRunShell.run(JobRunShell.java:216)
	at org.quartz.simpl.SimpleThreadPool$WorkerThread.run(SimpleThreadPool.java:549)
13:59:54,634 ERROR [IndexacionJob] Error intentando indexar
```

**Comment by slromero-indra** [comment]
Buenas, hemos observado que se produce un error en Utilidades.crearSolrClient(Utilidades.java:512) producido porque el valor es nulo, parece que la url no se pasa correctamente, como si no leyera correctamente la propiedad de la url.

Por favor, podéis comprobar si las siguientes propiedades están añadidas correctamente al jboss-service.xml:

        _
        es.caib.gusite.user.solr=admin
        es.caib.gusite.pass.solr=password
        es.caib.gusite.url.solr=localhost:8983/solr
        es.caib.gusite.index.solr=caib
	es.caib.gusite.solr.jobpendientes=0 0 2 * * ?

        
	es.caib.gusite.fecha.revision.accesibilidad=25/05/2015 
	es.caib.gusite.solr.tamanyomaximo=20
	es.caib.gusite.solr.ficheros=doc,docx,xls,xlsx,pdf,pdfx,odt,ods,odp,odf,txt,rtf_

**Comment by sgelabert-dgtic** [comment]
Corregit, efectivament era un problema amb els espais de les properties.

**Comment by sgelabert-dgtic** [comment]
Els nous objectes de BBDD no compleixen estandards:

CREATE TABLE GUS_SOLRPD
  (
    SLP_ID     NUMBER NOT NULL ENABLE,
    SLP_TIPO   VARCHAR2(128 CHAR),
    SLP_IDELEM NUMBER,
    SLP_ACCION NUMBER,
    SLP_FECCRE DATE,
    SLP_FECIDX DATE,
    SLP_RESULT    NUMBER,
    **SLP_TXTERR    VARCHAR2(300 BYTE) --> VARCHAR2(300 CHAR)**
    SLP_IDARCHIVO NUMBER,
    CONSTRAINT GUS_SOLRPD_PK PRIMARY KEY (SLP_ID)
  );
**CREATE SEQUENCE GUS_SEQSOLR; --> GUS_SLR_SEQ**

**Comment by sgelabert-dgtic** [comment]
Per coherència amb la nomenclatura de la resta de seqüències de la BBDD, s'accepta el nom GUS_SEQSOLR. No cal canviar-ho. Corregir únicament el BYTE per CHAR

**Comment by sgelabert-dgtic** [comment]
- Afegir informació sobre l'inici i final del procés d'indexació i possibles errades en la pantalla de Eines-->Indexació. Així com està no se sap si el procés a finalitzat o no o si hi hi hagut errades.
- El percentatge de similitud de la cerca sempre és del 15%
![cercador_similitud](https://cloud.githubusercontent.com/assets/17268396/20884538/2e86947c-baec-11e6-8155-8f5ac629231a.jpg)

**Comment by slromero-indra** [comment]
Se suben los cambios solicitados

**Comment by sgelabert-dgtic** [comment]
- Marcar el contingut no visible però indexat com a no disponible. Tal i com s'ha implementat a SEUCAIB
- Quan es presenta un hit sobre una pàgina HTML, reduir el text que es mostra de la pàgina a dues línies
- Eliminar el codi del contingut de la llista de resultats. Exemple: `463525 Site:`
- Pareix que la indexació del MS és sempre completa, és així ? Hi ha alguna manera d'indexar pendents ?

**Comment by slromero-indra** [comment]
Buenas, nos apuntamos las primeras tres tareas como pendientes. Sobre la última, fuera de un microsite, se puede ver los jobs ejecutados, indexar pendientes (de cualquier microsite) o indexación completa. Mientras que desde dentro de un microsite sólo se puede indexar completamente todo ese microsite.

No se ha incluido el indexar pendientes de sólo un microsite porque no vemos problema en indexar todos los pendientes de todos los microsites, ya que el coste de ejecutarlo es bajo.

**Comment by sgelabert-dgtic** [comment]
Afegeix-ho resum dels resultats de les darreres proves:
- La indexació de tots els microsites, indexació per UA ni la indexació per microsite no eliminen les indexacions pendents que hi pugui haver sobre continguts del microsite. Valorar si la incorporació d'una columna amb l'ID del microste en la taula de GUS_SOLRPD facilitaria el processament d'indexacions pendents.
- La indexació per UAs només indexa la UA en qüestió, quan hauria d'indexar tots els fills dependents de  la UA seleccionada.
- Quan es realitza una indexació total, el volum de dades de log es massa gran per mostrar-ho per pantalla i genera un error JS. Substituir el frame per la descàrrega d'un fitxer de log.
- Errades amb la indexació de pendents però que  **sí funcionen** amb la indexació de tot el microsite:
  - La indexació de pendents no elimina de la llista els casos de desindexació de continguts.
  - No funciona la desindexació de fitxers globals, agendes 
  - No funciona la indexació de preguntes/respostes associades a una enquesta
- S'obtenen percentatges associats a la rellevància dels continguts superiors al 100%

**Comment by slromero-indra** [comment]
Buenas, respecto a los puntos:
 - Al realizar una indexación total o por categoría, no se borra las indexaciones pendientes (tampoco en rolsac). Esto no tiene impacto porque simplemente se reindexaría de nuevo los elementos ya indexados. Si lo ves necesario, indicárnoslo y lo implementaremos para borrar los pendientes.
 - Lo habíamos preparada para una UA en concreto, lo actualizaremos para que tenga en cuenta los descendientes.
 - Cambiaremos en la visualización de  indexar todo para que se descargue el fichero txt en vez de visualizarlo.
 - Revisamos y os avisamos cuando lo solucionemos. 
 - Respecto al score, solr no devuelve un score porcentual normalizado al 100%, investigaremos sobre el tema para ver si se puede conseguir algo similar.

**Comment by episano-dgtic** [comment]
ok ahora se puede ver la evolución del proceso de la indexacion através de un fichero txt.

Fallos detectados:
1) El caso de la indexación por una unidad orgánica y sus descendientes. Únicamente mira el primer nivel de descendencia, y debe indexar todo el árbol de descendentes. Por otro lado viendo el resultado del .txt, indica como unidad orgánica el padre y no la unidad orgánica concreta. Me preocupa para cuando el buscador de web caib tenga en cuenta los microsites indique la uo concreta de donde procede.
2) Con indexación total, se ha quedado el proceso parado en el microsite 4005, o al menos no ha marcado la hora de finalización. Indexando 506 microsites de 540 microsites visibles. Un microsite que se seguro que no ha indexado es el 5265 ("Abril: Curs microsite 1). 

No he podido probar el resto, porque ahora no me permite indexar al quedar el sistema con una indexación pendiente pero que no termina. 




[resumen_microsites_pre3101.xlsx](https://github.com/GovernIB/gusite/files/741556/resumen_microsites_pre3101.xlsx)
![indexacion_pendiente](https://cloud.githubusercontent.com/assets/17451683/22459566/702d13f6-e7a1-11e6-86f3-4c7f92c5ea8a.gif)

**Comment by episano-dgtic** [comment]
Respecto a la indexación total, ahora funciona. La indexación duró 24 horas, 
30/01/2017 14:05 	31/01/2017 13:41

**Comment by episano-dgtic** [comment]
Ahora si dejas en blanco el buscador en el frontal da un error en el microsite 5265
![buscar_sindatos](https://cloud.githubusercontent.com/assets/17451683/22545130/d4636072-e937-11e6-8de0-fb90680fb2bf.gif)
En otro que he probado.. me sale un error que no encuentra la página solicitada. (https://proves.caib.es/sacmicrofront/cercar.do)

Respecto (Errades amb la indexació de pendents però que sí funcionen amb la indexació de tot el microsite:)    
      1)Sigue sin eliminarse los casos de desindexación, pese a que los desindexa en algun caso. Y no se ordenan por fecha de creación.
      2) Sigue sin funcionar la desindexació de fitxers globals. 
      3) En el caso de las agendas se desindexa el contenido del evento pero no el fichero que tuviera adjunto pese a que se elimina. 

Ni en indexación pendiente ni por microsite, en los formularios de contacto no se indexan los campos solicita, no recuerdo ahora si debería hacerse.

**Comment by episano-dgtic** [comment]
Por cierto, no he visto ninguna solución para el caso que salvador comentaba:
"Marcar el contingut no visible però indexat com a no disponible. Tal i com s'ha implementat a SEUCAIB"

**Comment by slromero-indra** [comment]
buenas,
Referente al pantallazo (búsqueda vacía) nos podéis facilitar la exportación del microsite que os da problemas?  hemos incorporado un control que solventa esta problemática, pero convendría validar la solución con el mismo microsite.
Hemos tratado los puntos 1, 2 y 3, y ya están comiteados.
Respecto al tema de "no disponible" estamos tratando de incorporarlo a gusite.

**Comment by slromero-indra** [comment]
Referente al pantallazo (búsqueda vacía) nos podéis facilitar la exportación del microsite que os da problemas? hemos incorporado un control que solventa esta problemática, pero convendría validar la solución con el mismo microsite.

Por otro lado ya se ha incluido el tema de marcar contenido no visible pero indexado, como No disponible.

**Comment by episano-dgtic** [comment]
Primero, recuerda asignarme a la incidencia porque sino no me percato que precisas alguna información. 

Segundo, te remito el microsite exportado. 
[curso1.zip](https://github.com/GovernIB/gusite/files/830731/curso1.zip)

Por último, me acabo de percatar que la ventana de indexación de un microsite es común para todos los microsites. 
![indexacion_microsite](https://cloud.githubusercontent.com/assets/17451683/23749378/32e7394c-04c8-11e7-8e75-494d069197a3.gif)

No debería ver como ha evolucionado la indexación únicamente de dicho microsite?.  De modo que si no se ha indexado nunca no hubiera ninguna referencia. SI ahora eligo otro microsite, veo el mismo historial siempre, y se añadiría la indexación iniciada nueva si lo hago.

**Comment by slromero-indra** [comment]
Añadido una columna más para indicar el microsite y poder filtrar la información a mostrar según el microsite (se va a proceder a poner en los sql).

ALTER TABLE GUS_SOLJOB ADD JOB_IDELEM NUMBER(19,0);
