### ISSUE TITLE
CAso front sites. Problema de visualización de páginas cuando tienen un componente con alguna noticia que no tenga fecha de publicación 

### ISSUE THREAD

**Issue by episano-dgtic** [GovernIB/gusite#65]
Si una página tiene un componente que hace referencia a un listado, y dicho componente trata de mostrar un elemento sin fecha de publicación hace que aparezca la página vacia.  En el antiguo front eso no ocurría. 

Para que lo repliquéis en vuestro entorno. Microsite Variado site->carpeta Animal2->página "Problema componente"
http://caibter.indra.es/sites/Mexotics/problema_componente/

Adjunto error de logs:
`2016-11-09 13:19:01,770 ERROR [org.thymeleaf.TemplateEngine] (http-10.215.9.207-18080-28) [THYMELEAF][http-10.215.9.207-18080-28] Exception processing template "devdb:2075": Error formatting date with format pattern "dd/MM/yyyy" (devdb:2075:84)
2016-11-09 13:19:01,770 ERROR [es.caib.gusite.front.thymeleaf.GusiteTemplateProcessor] (http-10.215.9.207-18080-28) org.thymeleaf.exceptions.TemplateProcessingException: Error formatting date with format pattern "dd/MM/yyyy" (devdb:2075:84)
2016-11-09 13:19:01,770 ERROR [es.caib.gusite.front.microtag.MicrositeParser] (http-10.215.9.207-18080-28) Se ha producido un error parseando html. 
java.lang.RuntimeException: Could not run template: devdb:2075:: componenteListaNoticias
	at es.caib.gusite.front.thymeleaf.GusiteTemplateProcessor.process(GusiteTemplateProcessor.java:67)
	at es.caib.gusite.front.microtag.MicrositeParser.getHtmlComponenteTNoticia(MicrositeParser.java:596)
	at es.caib.gusite.front.microtag.MicrositeParser.getHtmlElementosComponente(MicrositeParser.java:510)
	at es.caib.gusite.front.microtag.MicrositeParser.doCalculaTags(MicrositeParser.java:415)
	at es.caib.gusite.front.microtag.MicrositeParser.doParser(MicrositeParser.java:250)
	at es.caib.gusite.front.contenido.ContenidoController.reemplazarTags(ContenidoController.java:359)
	at es.caib.gusite.front.contenido.ContenidoController.contenido(ContenidoController.java:183)
	at es.caib.gusite.front.contenido.ContenidoController.contenidoSmart(ContenidoController.java:91)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.web.method.support.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:219)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:132)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:104)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandleMethod(RequestMappingHandlerAdapter.java:746)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:687)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:80)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:925)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:856)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:915)
	at org.springframework.web.servlet.FrameworkServlet.doGet(FrameworkServlet.java:811)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:617)
	at org.springframework.web.servlet.FrameworkServlet.service(FrameworkServlet.java:796)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:717)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:290)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.springframework.web.filter.CharacterEncodingFilter.doFilterInternal(CharacterEncodingFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.tuckey.web.filters.urlrewrite.RuleChain.handleRewrite(RuleChain.java:176)
	at org.tuckey.web.filters.urlrewrite.RuleChain.doRules(RuleChain.java:145)
	at org.tuckey.web.filters.urlrewrite.UrlRewriter.processRequest(UrlRewriter.java:92)
	at org.tuckey.web.filters.urlrewrite.UrlRewriteFilter.doFilter(UrlRewriteFilter.java:394)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.jboss.web.tomcat.filters.ReplyHeaderFilter.doFilter(ReplyHeaderFilter.java:96)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:235)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206)
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:235)
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:191)
	at org.jboss.web.tomcat.security.SecurityAssociationValve.invoke(SecurityAssociationValve.java:183)
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:442)
	at org.jboss.web.tomcat.security.JaccContextValve.invoke(JaccContextValve.java:95)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.process(SecurityContextEstablishmentValve.java:126)
	at org.jboss.web.tomcat.security.SecurityContextEstablishmentValve.invoke(SecurityContextEstablishmentValve.java:70)
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:127)
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:102)
	at org.jboss.web.tomcat.service.jca.CachedConnectionValve.invoke(CachedConnectionValve.java:158)
	at es.caib.loginModule.auth.FormResourcesValve.invoke(FormResourcesValve.java:31)
	at es.caib.loginModule.auth.ClientIPValve.invoke(ClientIPValve.java:62)
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:109)
	at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.internalProcess(ActiveRequestResponseCacheValve.java:74)
	at org.jboss.web.tomcat.service.request.ActiveRequestResponseCacheValve.invoke(ActiveRequestResponseCacheValve.java:47)
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:330)
	at org.apache.coyote.http11.Http11Processor.process(Http11Processor.java:829)
	at org.apache.coyote.http11.Http11Protocol$Http11ConnectionHandler.process(Http11Protocol.java:599)
	at org.apache.tomcat.util.net.JIoEndpoint$Worker.run(JIoEndpoint.java:451)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.thymeleaf.exceptions.TemplateProcessingException: Error formatting date with format pattern "dd/MM/yyyy" (devdb:2075:84)
	at org.thymeleaf.expression.Dates.format(Dates.java:186)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.springframework.expression.spel.support.ReflectiveMethodExecutor.execute(ReflectiveMethodExecutor.java:69)
	at org.springframework.expression.spel.ast.MethodReference$MethodValueRef.getValue(MethodReference.java:73)
	at org.springframework.expression.spel.ast.CompoundExpression.getValueInternal(CompoundExpression.java:81)
	at org.springframework.expression.spel.ast.SpelNodeImpl.getValue(SpelNodeImpl.java:93)
	at org.springframework.expression.spel.standard.SpelExpression.getValue(SpelExpression.java:94)
	at org.thymeleaf.spring3.expression.SpelVariableExpressionEvaluator.evaluate(SpelVariableExpressionEvaluator.java:139)
	at org.thymeleaf.standard.expression.VariableExpression.executeVariable(VariableExpression.java:149)
	at org.thymeleaf.standard.expression.SimpleExpression.executeSimple(SimpleExpression.java:59)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:103)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:133)
	at org.thymeleaf.standard.expression.Expression.execute(Expression.java:120)
	at org.thymeleaf.standard.processor.attr.AbstractStandardTextChildModifierAttrProcessor.getText(AbstractStandardTextChildModifierAttrProcessor.java:68)
	at org.thymeleaf.processor.attr.AbstractTextChildModifierAttrProcessor.getModifiedChildren(AbstractTextChildModifierAttrProcessor.java:59)
	at org.thymeleaf.processor.attr.AbstractChildrenModifierAttrProcessor.processAttribute(AbstractChildrenModifierAttrProcessor.java:58)
	at org.thymeleaf.processor.attr.AbstractAttrProcessor.doProcess(AbstractAttrProcessor.java:87)
	at org.thymeleaf.processor.AbstractProcessor.process(AbstractProcessor.java:212)
	at org.thymeleaf.dom.Node.applyNextProcessor(Node.java:1016)
	at org.thymeleaf.dom.Node.processNode(Node.java:971)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:672)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:655)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:672)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:655)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:672)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:655)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:672)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:655)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:672)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:655)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.NestableNode.computeNextChild(NestableNode.java:672)
	at org.thymeleaf.dom.NestableNode.doAdditionalProcess(NestableNode.java:655)
	at org.thymeleaf.dom.Node.processNode(Node.java:990)
	at org.thymeleaf.dom.Document.process(Document.java:93)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1155)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1060)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:1011)
	at org.thymeleaf.TemplateEngine.process(TemplateEngine.java:924)
	at es.caib.gusite.front.thymeleaf.GusiteTemplateProcessor.process(GusiteTemplateProcessor.java:60)
	... 59 more
Caused by: java.lang.IllegalArgumentException: Cannot apply format on null
	at org.thymeleaf.util.Validate.notNull(Validate.java:37)
	at org.thymeleaf.util.DateUtils.format(DateUtils.java:290)
	at org.thymeleaf.expression.Dates.format(Dates.java:184)
	... 105 more`

**Comment by episano-dgtic** [comment]
Incluyendo otro error similar al anterior. **Si el listado es de tipo enlace, y no se incluye una url en algun elemento del listado. Hace como en el caso anterior que no se muestre la página en blanco.** 

Adicionalmente para seguir con el mismo criterio antiguo front en la visualización de los componentes:

1) Si el listado es de tipo ficha si los elementos no tienen imagen, aparece la referencia al título dos veces. Eliminar la primera referencia. Si el elemento tiene imagen es correcto que aparezca la imagen como aparece.
![componente_listadoficha_sin imagen](https://cloud.githubusercontent.com/assets/17451683/20170947/b9f74f3c-a72e-11e6-840a-7a79912ad40e.gif)

Si el listado es de tipo documento o enlace, no debería aparecer ninguna referencia a imagen, ya que de partida no se incluyen. Como mucho como era anteriormente en formato lista (*)
![componente_listadodocumento_sites](https://cloud.githubusercontent.com/assets/17451683/20170942/b5abe35c-a72e-11e6-94df-b5abf2c8b69c.gif)

Para quede claro a lo que me refiero, antes se veían lis componentes de los listados de enlace y documento así:
![componente_listadodocumento_antes](https://cloud.githubusercontent.com/assets/17451683/20170951/beecbbb2-a72e-11e6-901b-a21ffc02e79e.gif)

2) Si os fijáis en la imagenes anteriores:

![componente_listadodocumento_antes](https://cloud.githubusercontent.com/assets/17451683/20170988/fa90f6ce-a72e-11e6-9bb9-40208d82a648.gif)
![componente_listadodocumento_sites](https://cloud.githubusercontent.com/assets/17451683/20170993/ffa2e94c-a72e-11e6-99f3-9142ce1053e6.gif)

 respecto al campo Texto de los elementos del listado, en los listados de tipo documentos y enlaces no aparecen los textos.  Deberían aparecer
(please que no haya el problema que ocurre con la fecha y la url que se está vacio se quedarán la página en blanco)

**Comment by episano-dgtic** [comment]
La imagen de como se mostraba los componentes de los listados de tipo documento o enlace antes:

![componente_listadodocumento_antes](https://cloud.githubusercontent.com/assets/17451683/20168666/a4a39970-a723-11e6-9a8f-d970e1b24bbd.gif)

**Comment by episano-dgtic** [comment]
Asumía que los errores de este tipo se solventaban para el tema por defecto y el personalizado. 
Con el tema personalizado de indra.. sigue quedando la página vacía en los casos de falta de los campos comentados, en los listados tipo ficha y documento. 

Otro bug detectado ahora: En los componentes de tipo enlace no remite a la url indicada, ya sea con url absoluta (http://www.uib.es) o relativa (contenido.do?idsite=157&cont=64458)

**Comment by slromero-indra** [comment]
Buenas, hemos realizado las pruebas sobre el primer punto y no hemos sido capaces de replicarlo. Por favor, podéis revisar a importar de nuevo el zip en el estilo creado por si hubiese habido algún problema con el tema2015.zip. Igualmente, hemos subido de nuevo el zip que sólo incluye un cambio observado con el icono 'bullet' (el icono de lista) para que no tuviese un tamaño más grande en un tipo de lista. Se puede ver el resultado del primer punto en este site: http://caibter.indra.es/sites/Mexotics/

Sobre el segundo punto, ya están realizados los cambios también.

Se recomienda realizar las pruebas mejor sobre el entorno caib (en nuestro entorno de desarrollo, si no es un site revisado, hay posibilidad de que algún documento/imagen se encuentre vacío dando falsos errores).

**Comment by episano-dgtic** [comment]
Repecto;"Asumía que los errores de este tipo se solventaban para el tema por defecto y el personalizado.
Con el tema personalizado de indra.. sigue quedando la página vacía en los casos de falta de los campos comentados, en los listados tipo ficha y documento." correcto, se solventa actualizando el tema personalizado. 
Please indicad que se actualice el tema cuando sea necesario. 
Para el segundo bug.. cuando salvador suba la nueva versión os digo.

**Comment by episano-dgtic** [comment]
Acabo de detectar con si tratas de acceder a la página del componente en castellano da un error.

**Comment by episano-dgtic** [comment]
Cuando se elimina un componente previamente incluido en alguna página. Al visualizar dicha página, se muestra vacía, pese a que tuviera más contenidos.

Os he replicar el problema del componente en vuestro entorno. Concretamente en la página:
http://caibter.indra.es/sites/M161103080140629/ca/pagina_con_un_componente_se_elimina/
Para ello, se crea un listado, y el componente asociado. Se crea una página y se añade el componente con texto adicional. Y posteriormente se elimina el componente.
Veréis que muestra la página vacia, entiendo porque se da un error al tratar de ver el componente eliminado.

**Comment by slromero-indra** [comment]
Buenas, nos vendría muy bien que no se reabrieran incidencias para poder llevar un mejor control de los temas tratados, y poder ir cerrando aquellos temas que ya están solventados. Si nos creáis una incidencia nueva por cada problemática, es mucho más fácil tanto que la verifiquéis como seguir el avance de las diferentes incidencias.

Podríais crearnos una nueva incidencia con esta nueva casuística y cerrar esta? aunque afecte a componentes el problema descrito en esta incidencia no es el mismo, y la problemática original ya está solventada.

**Comment by episano-dgtic** [comment]
Desde nuestro pto de vista se trata de una problemática que el anterior front no tenía. El nuevo lo ha tenido desde que se parió, y que continuó sin solventarse ni detectarse tras esta incidencia. A sido ahora que se ha detectado. 

Lo ideal es que se hubiera pensado en la implementación, o se hubieran hecho un testeo para asegurarse de la no existencia de bugs por dicho componente. 

Estarás de acuerdo conmigo que tampoco es cuestión de pedir una mejora, y la corrección de todos los bugs que vayan apareciendo por la implementación de dicha mejora vayan siendo varias nuevas incidencias. Sino como mucho una incidencia que recopila la problemáticas relacionadas, que en el caso ideal nunca debería haber ocurrido. 
Mirando las estadísticas actuales de gusite, hay 24 incidencias de mejoras frente a 38 de bugs. Si hago lo que me dices, el score de bugs aumentará. Y parecerá que nos dedicamos más a resolver bugs que a implementar mejoras.

**Comment by slromero-indra** [comment]
Ok, lo trataremos en esta incidencia.

**Comment by episano-dgtic** [comment]
Lo he probado en caibter y en caib, y en ambos entornos sigue ocurriendo la incidencia. 
http://caibter.indra.es/sites/M161103080140629/ca/pagina_con_un_componente_se_elimina/

**Comment by slromero-indra** [comment]
Buenas, lo acabamos de actualizar en caibter, podeis volverlo a verificar?

Hemos desplegado los cambios también a la rama 1.2.

**Comment by episano-dgtic** [comment]
He visualizado la página y parece va bien en vuestro entorno.
