### ISSUE TITLE
Bug acces backoffice

### ISSUE THREAD

**Issue by sgelabert-dgtic** [GovernIB/gusite#69]
Adjunt errada que impedeix accés al backoffice 
```
09:36:19,303 ERROR [[jsp]] El Servlet.service() para servlet jsp lanzó una excepción
javax.servlet.jsp.JspException: Missing message for key "menu.indexar.principal"
	at org.apache.struts.taglib.bean.MessageTag.doStartTag(MessageTag.java:297)
	at org.apache.jsp.menuLateralIzq_jsp._jspx_meth_bean_005fmessage_005f7(menuLateralIzq_jsp.java:397)
	at org.apache.jsp.menuLateralIzq_jsp._jspService(menuLateralIzq_jsp.java:193)
	at org.apache.jasper.runtime.HttpJspBase.service(HttpJspBase.java:70)
```

**Comment by sgelabert-dgtic** [comment]
Es tractava d'un problema de temporals.
